---
version: "3.8"

services:

  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry
    volumes:
      - "registry:/mnt/registry"

#  pinger:
#    image: "localhost:5000/net"
#    command: ["ping", "google.com"]
#    deploy:
#      mode: global
#    depends_on:
#      - "registry"

  flask:
    image: "localhost:5000/flask"
    deploy:
      mode: "replicated"
      replicas: 2
    secrets:
      - image_gallery_password
    configs:
      - source: flask_config
        target: /etc/flask.config
        mode: 0444
    depends_on:
      - "registry"

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    deploy:
      mode: "replicated"
      replicas: 1
    volumes:
            - "image-gallery-postgres:/var/lib/postgresql/data"

volumes:
  registry:
  image-gallery-postgres:
    driver: rexray/efs

secrets:
  image_gallery_password:
    external: true

configs:
  flask_config:
    file: flask.config
