---
version 3

services:
    
    db:
        image: database
        user: "image_gallery"
        volumes:
            - "/home/ec2-user/secrets:/mnt/secrets
            - "demo-postgres:/var/lib/postgresql/data"
    
    web:
        image: image_gallery
        user: "test"
        environment:
            PG_HOST: "db"
            PG_PORT: "5432"
            IG_USER: "image_gallery"
            IG_PASSWD_FILE: "/mnt/secrets/postgres_passwd"
            IG_DATABASE: "database"
        ports:
            - "5000:8888"
        volumes:
            - "/home/ec2-user/secrets:/mnt/secrets"
        depends_on:
            - "db"
        

volumes:
    demo-postgres:
        external: true

