---
version: "3"

services:

  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry
    volumes:
      - "registry:/mnt/registry"

#  pinger:
#    image: "localhost:5000/net"
#    command: ["ping", "google.com"]
#    deploy:
#      mode: global
#    depends_on:
#      - "registry"

  flask:
    image: "localhost:5000/flask"
    deploy:
      mode: "replicated"
      replicas: 2
    depends_on:
      - "registry"

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "/run/secrets/ig_password"
      POSTGRES_USER: image_gallery
      POSTGRES_DB: postgres
      PGDATA: /mnt/image-gallery-postgres/pgdata
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - node.labels.database==yes
    volumes:
      - "/home/ec2-user/image-gallery-postgres:/mnt/image-gallery-postgres"

volumes:
  registry:
