---
version: "3"

services:

  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry
    volumes:
      - "registry:/mnt/registry"

  flask:
    image: "localhost:5000/flask"
    deploy:
      mode: "replicated"
      replicas: 2
      placement:
        constraints:
          - node.labels.flask_server!=yes
    depends_on:
      - "registry"

  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    deploy:
      replicas: 1
    volumes:
      - "image-gallery-postgres:/var/lib/postgresql/data"

volumes:
     registry:
     image-gallery-postgres:
     driver: rexray/efs
