---
plugin: aws_ec2
regions:
  - us-west-1
keyed_groups:
  - key: tags.Name
    prefix: tag_Name_
    separator: ""
  - key: tags.Module
    prefix: tag_Module__
    separator: ""
  - key: tags.Department
    prefix: tag_Department_
    separator: ""
