---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id:
  module_defaults:
    group/aws:
      profile:
      region: "us-west-1"
  tasks:
    - name: Provision EC2 instance
      ec2:
        key_name: auburnec2
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id}}"
        instance_tags:
          Name: Module5 EC2
          Module: 5
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: Module5 EC2
    
             

